spring:
  application:
    name: rag-chat

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${DB_USERNAME:chatuser}
    password: ${DB_PASSWORD:chatpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  api-key: ${API_KEY:2d4ac50ee70a28beb45ad9e4417c76abd35de414e073615ec0e6661387b13636}

springdoc:
  swagger-ui:
    path: /swagger-ui.html